<template>
  <section class="ym-smart-list" :dir="locale === 'ar' ? 'rtl' : 'ltr'" :aria-busy="loading">
    <div class="ym-smart-list__view-controls" :aria-label="text.viewControls">
      <label><span>{{ text.metric }}</span><select :value="metric" @change="changeMetric"><option v-for="option in metricOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label>
      <label><span>{{ text.date }}</span><select :value="dateField" @change="changeDate"><option v-for="option in dateOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label>
      <button type="button" :aria-label="text.toggleDirection" @click="$emit('direction-change', currentControlKind)"><span>{{ text.direction }}</span><b>{{ direction === 'desc' ? text.descending : text.ascending }}</b><i aria-hidden="true">{{ direction === 'desc' ? '↓' : '↑' }}</i></button>
    </div>

    <p v-if="updating" class="ym-smart-list__update is-progress" role="status" aria-live="polite">{{ text.updating }}</p>
    <p v-if="error && items.length" class="ym-smart-list__update is-error" role="alert">{{ error }} <button type="button" @click="$emit('retry')">{{ text.retry }}</button></p>
    <p v-if="summaryWarning" class="ym-smart-list__update is-warning" role="status">{{ summaryWarning }}</p>

    <div v-if="loading && items.length === 0" class="ym-smart-list__state" role="status" aria-live="polite">
      <span class="ym-smart-list__spinner" aria-hidden="true" /><strong>{{ text.loading }}</strong><p>{{ text.loadingCopy }}</p>
    </div>
    <div v-else-if="error && items.length === 0" class="ym-smart-list__state is-error" role="alert">
      <strong>{{ text.error }}</strong><p>{{ error }}</p><button type="button" @click="$emit('retry')">{{ text.retry }}</button>
    </div>
    <div v-else-if="items.length === 0" class="ym-smart-list__state">
      <strong>{{ text.empty }}</strong><p>{{ text.emptyCopy }}</p><div><button type="button" @click="$emit('reset')">{{ text.reset }}</button><NuxtLink v-if="canCreate" to="/admin/works/create">{{ text.create }}</NuxtLink></div>
    </div>
    <template v-else>
      <div class="ym-smart-list__desktop">
        <table>
          <colgroup><col class="is-select" /><col class="is-work" /><col class="is-status" /><col class="is-team" /><col class="is-taxonomy" /><col class="is-dynamic" /><col class="is-date" /><col class="is-actions" /></colgroup>
          <thead><tr>
            <th class="is-select"><input v-if="canSelect" type="checkbox" :checked="allSelected" :aria-label="text.selectPage" @change="$emit('toggle-page')" /></th>
            <th class="is-work">{{ text.work }}</th><th class="is-status">{{ text.status }}</th><th class="is-team">{{ text.team }}</th><th class="is-taxonomy">{{ text.taxonomy }}</th>
            <th class="is-dynamic"><span class="ym-smart-list__head-title">{{ text.engagement }}</span><div class="ym-smart-list__head-control"><label><span class="sr-only">{{ text.metric }}</span><select :value="metric" @change="changeMetric"><option v-for="option in metricOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><button type="button" :aria-label="text.toggleDirection" @click="$emit('direction-change', 'metric')">{{ direction === 'desc' ? '↓' : '↑' }}</button></div></th>
            <th class="is-date"><span class="ym-smart-list__head-title">{{ text.dateHeading }}</span><div class="ym-smart-list__head-control"><label><span class="sr-only">{{ text.date }}</span><select :value="dateField" @change="changeDate"><option v-for="option in dateOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><button type="button" :aria-label="text.toggleDirection" @click="$emit('direction-change', 'date')">{{ direction === 'desc' ? '↓' : '↑' }}</button></div></th>
            <th class="is-actions">{{ text.actions }}</th>
          </tr></thead>
          <tbody><tr v-for="work in items" :key="work.id" :class="`is-status-${work.status}`">
            <td class="is-select"><input v-if="canSelect" type="checkbox" :checked="isSelected(work.id)" :disabled="!isSelected(work.id) && selectionAtLimit" :aria-label="text.selectWork(work.title)" @change="$emit('toggle-work', work)" /></td>
            <td class="is-work">
              <WorksIndexInfoPopover :label="text.workInfo" :hint="text.openInfo" :close-label="text.close">
                <template #trigger><span class="ym-smart-list__work"><strong :dir="textDirection(work.title)">{{ work.title }}</strong><small><MediaIcon :type="work.media_type" />{{ mediaLabel(work.media_type) }}</small></span></template>
                <dl class="ym-smart-list__popover-list"><div><dt>{{ text.title }}</dt><dd>{{ work.title }}</dd></div><div><dt>{{ text.slug }}</dt><dd dir="ltr">{{ work.slug }}</dd></div><div><dt>{{ text.summary }}</dt><dd>{{ work.summary || text.none }}</dd></div><div><dt>{{ text.media }}</dt><dd>{{ mediaLabel(work.media_type) }}</dd></div><div><dt>{{ text.price }}</dt><dd>{{ work.price_amount || text.none }}</dd></div><div><dt>{{ text.delivery }}</dt><dd>{{ work.delivery_days === null ? text.none : formatNumber(work.delivery_days) }}</dd></div></dl>
              </WorksIndexInfoPopover>
            </td>
            <td class="is-status">
              <WorksIndexInfoPopover :label="text.statusInfo" :hint="text.openInfo" :close-label="text.close">
                <template #trigger><span class="ym-smart-list__status"><b :class="`is-${work.status}`">{{ statusLabel(work.status) }}</b><small>{{ visibilityLabel(work.visibility_status) }}<FeaturedIcon v-if="work.is_featured" /><PinIcon v-if="work.is_pinned" /></small></span></template>
                <dl class="ym-smart-list__popover-list"><div><dt>{{ text.workStatus }}</dt><dd>{{ statusLabel(work.status) }}</dd></div><div><dt>{{ text.visibility }}</dt><dd>{{ visibilityLabel(work.visibility_status) }}</dd></div><div><dt>{{ text.featured }}</dt><dd>{{ yesNo(work.is_featured) }}</dd></div><div><dt>{{ text.pinned }}</dt><dd>{{ yesNo(work.is_pinned) }}</dd></div></dl>
              </WorksIndexInfoPopover>
            </td>
            <td class="is-team">
              <WorksIndexInfoPopover :label="text.teamInfo" :hint="text.openInfo" :close-label="text.close">
                <template #trigger><span class="ym-smart-list__team"><small>{{ text.designer }}</small><strong>{{ work.designer?.name || text.unassigned }}</strong><small>{{ text.reviewer }}</small><strong>{{ work.reviewer?.name || text.unassigned }}</strong></span></template>
                <dl class="ym-smart-list__popover-list"><div><dt>{{ text.designer }}</dt><dd>{{ work.designer?.name || text.unassigned }}</dd></div><div><dt>{{ text.reviewer }}</dt><dd>{{ work.reviewer?.name || text.unassigned }}</dd></div></dl>
              </WorksIndexInfoPopover>
            </td>
            <td class="is-taxonomy">
              <WorksIndexInfoPopover :label="text.taxonomyInfo" :hint="text.openInfo" :close-label="text.close">
                <template #trigger><span class="ym-smart-list__taxonomy"><strong>{{ categoryLabel(work) }}</strong><small>{{ tagsSummary(work) }}</small></span></template>
                <div class="ym-smart-list__taxonomy-detail"><strong>{{ categoryLabel(work) }}</strong><small v-if="work.taxonomy.category">{{ work.taxonomy.category.is_active ? text.active : text.disabled }}</small><p v-if="work.taxonomy.tags === null">{{ text.unavailable }}</p><p v-else-if="work.taxonomy.tags.length === 0">{{ text.noTags }}</p><ul v-else><li v-for="tag in work.taxonomy.tags" :key="tag.id" :class="{ 'is-disabled': !tag.is_active }">{{ taxonomyName(tag) }} <small v-if="!tag.is_active">{{ text.disabled }}</small></li></ul></div>
              </WorksIndexInfoPopover>
            </td>
            <td class="is-dynamic">
              <WorksIndexInfoPopover :label="text.engagementInfo" :hint="text.openInfo" :close-label="text.close">
                <template #trigger><span class="ym-smart-list__number" :class="{ 'is-alert': metric === 'reports_count' && work.reports_count > 0 }">{{ formatNumber(work[metric]) }}<span v-if="work.reports_count > 0" class="sr-only">{{ text.hasReports }}</span></span></template>
                <dl class="ym-smart-list__popover-list"><div><dt>{{ text.views }}</dt><dd>{{ formatNumber(work.views_count) }}</dd></div><div><dt>{{ text.likes }}</dt><dd>{{ formatNumber(work.likes_count) }}</dd></div><div :class="{ 'is-alert': work.reports_count > 0 }"><dt>{{ text.reports }}</dt><dd>{{ formatNumber(work.reports_count) }}</dd></div></dl>
              </WorksIndexInfoPopover>
            </td>
            <td class="is-date">
              <WorksIndexInfoPopover :label="text.dateInfo" :hint="text.openInfo" :close-label="text.close">
                <template #trigger><time class="ym-smart-list__date" :datetime="work[dateField] || undefined">{{ formatDate(work[dateField]) }}</time></template>
                <dl class="ym-smart-list__popover-list"><div v-for="option in dateOptions" :key="option.value"><dt>{{ option.label }}</dt><dd class="is-date-value">{{ formatDateTime(work[option.value]) }}</dd></div></dl>
              </WorksIndexInfoPopover>
            </td>
            <td class="is-actions"><ActionButtons :work="work" :can-edit="canEditWork(work)" :can-details="canViewDetails" :can-taxonomy="canManageTaxonomy" :text="text" @details="$emit('details', work)" @taxonomy="$emit('taxonomy', work)" /></td>
          </tr></tbody>
        </table>
      </div>

      <div class="ym-smart-list__mobile">
        <article v-for="work in items" :key="work.id">
          <header><input v-if="canSelect" type="checkbox" :checked="isSelected(work.id)" :disabled="!isSelected(work.id) && selectionAtLimit" :aria-label="text.selectWork(work.title)" @change="$emit('toggle-work', work)" /><div><strong :dir="textDirection(work.title)">{{ work.title }}</strong></div><span class="ym-smart-list__status"><b :class="`is-${work.status}`">{{ statusLabel(work.status) }}</b></span></header>
          <div class="ym-smart-list__mobile-meta"><span><MediaIcon :type="work.media_type" />{{ mediaLabel(work.media_type) }}</span><span>{{ visibilityLabel(work.visibility_status) }}<FeaturedIcon v-if="work.is_featured" /><PinIcon v-if="work.is_pinned" /></span></div>
          <dl><div><dt>{{ text.team }}</dt><dd class="is-team-lines"><span>{{ text.designer }}: {{ work.designer?.name || text.unassigned }}</span><span>{{ text.reviewer }}: {{ work.reviewer?.name || text.unassigned }}</span></dd></div><div><dt>{{ text.taxonomy }}</dt><dd>{{ categoryLabel(work) }} · {{ tagsSummary(work) }}</dd></div><div><dt>{{ metricLabel }}</dt><dd class="is-number">{{ formatNumber(work[metric]) }}</dd></div><div><dt>{{ dateLabel }}</dt><dd class="is-date-value">{{ formatDate(work[dateField]) }}</dd></div></dl>
          <footer><WorksIndexInfoPopover :label="text.moreInfo" :hint="text.openInfo" :close-label="text.close"><template #trigger><span class="ym-smart-list__more">{{ text.moreInfo }}</span></template><dl class="ym-smart-list__popover-list"><div><dt>{{ text.views }}</dt><dd>{{ formatNumber(work.views_count) }}</dd></div><div><dt>{{ text.likes }}</dt><dd>{{ formatNumber(work.likes_count) }}</dd></div><div><dt>{{ text.reports }}</dt><dd>{{ formatNumber(work.reports_count) }}</dd></div><div v-for="option in dateOptions" :key="option.value"><dt>{{ option.label }}</dt><dd class="is-date-value">{{ formatDateTime(work[option.value]) }}</dd></div></dl></WorksIndexInfoPopover><ActionButtons :work="work" :can-edit="canEditWork(work)" :can-details="canViewDetails" :can-taxonomy="canManageTaxonomy" :text="text" @details="$emit('details', work)" @taxonomy="$emit('taxonomy', work)" /></footer>
        </article>
      </div>

      <footer class="ym-smart-list__pagination"><span :aria-label="footerAriaLabel">{{ summary ? text.showing(formatNumber(summary.visible_on_page), formatNumber(summary.total_filtered)) : text.summaryUnavailable }}</span><nav :aria-label="text.pagination"><button type="button" :disabled="loading || pagination.current_page <= 1" @click="$emit('page', pagination.current_page - 1)">{{ text.previous }}</button><b>{{ text.pageOf(formatNumber(pagination.current_page), formatNumber(pagination.last_page)) }}</b><button type="button" :disabled="loading || pagination.current_page >= pagination.last_page" @click="$emit('page', pagination.current_page + 1)">{{ text.next }}</button></nav></footer>
    </template>
  </section>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, watch } from 'vue'
import WorksIndexFloatingOverlay from './WorksIndexFloatingOverlay.vue'
import WorksIndexInfoPopover from './WorksIndexInfoPopover.vue'
import { formatYmDate, formatYmDateTime, formatYmNumber } from '~/utils/ymFormatting'

type MetricKey = 'views_count' | 'likes_count' | 'reports_count'
type DateKey = 'created_at' | 'updated_at' | 'submitted_at' | 'reviewed_at' | 'approved_at' | 'published_at' | 'rejected_at' | 'hidden_at' | 'archived_at'
interface Entity { id: number; name_ar: string; name_en: string; is_active: boolean }
interface WorkItem { id: number; title: string; slug: string; summary: string | null; status: string; visibility_status: string; media_type: string | null; price_amount: string | null; delivery_days: number | null; designer: { id: number; name: string } | null; reviewer: { id: number; name: string } | null; category_id: number | null; is_featured: boolean; is_pinned: boolean; reports_count: number; views_count: number; likes_count: number; created_at: string | null; updated_at: string | null; submitted_at: string | null; reviewed_at: string | null; approved_at: string | null; published_at: string | null; rejected_at: string | null; hidden_at: string | null; archived_at: string | null; taxonomy: { category: Entity | null; category_tracking: { is_legacy_unmapped: boolean; is_uncategorized: boolean } | null; tags: Entity[] | null } }
interface Summary { total_filtered: number; visible_on_page: number; published_filtered: number; review_cycle_filtered: number; reported_filtered: number }
interface TextCopy { [key: string]: any }
const props = defineProps<{ locale: 'ar' | 'en'; items: WorkItem[]; pagination: { current_page: number; total: number; last_page: number }; summary: Summary | null; summaryWarning: string | null; loading: boolean; updating: boolean; error: string | null; metric: MetricKey; dateField: DateKey; sort: string; direction: 'asc' | 'desc'; canSelect: boolean; selectedIds: number[]; selectionAtLimit: boolean; canViewDetails: boolean; canManageTaxonomy: boolean; canCreate: boolean; canEditWork: (work: WorkItem) => boolean }>()
const copies = {
  ar: { loading: 'جارٍ تحميل الأعمال', loadingCopy: 'يتم جلب أحدث نتيجة مطابقة للفلاتر.', updating: 'جارٍ تحديث النتائج مع إبقاء آخر بيانات متناسقة…', error: 'تعذر تحميل قائمة الأعمال', retry: 'إعادة المحاولة', empty: 'لا توجد أعمال مطابقة.', emptyCopy: 'جرّب إعادة ضبط الفلاتر أو إنشاء عمل جديد.', reset: 'إعادة ضبط الفلاتر', create: 'إنشاء عمل جديد', selectPage: 'تحديد الصفحة الحالية', selectWork: (title: string) => `تحديد العمل ${title}`, work: 'العمل', status: 'الحالة', team: 'الفريق', taxonomy: 'التصنيف والوسوم', engagement: 'التفاعل', metric: 'مؤشر التفاعل', date: 'نوع التاريخ', dateHeading: 'التاريخ', direction: 'اتجاه الفرز', descending: 'تنازلي', ascending: 'تصاعدي', viewControls: 'أدوات عرض البطاقات', toggleDirection: 'تغيير اتجاه الفرز', actions: 'الإجراءات', workInfo: 'معلومات العمل', statusInfo: 'معلومات الحالة', teamInfo: 'معلومات الفريق', taxonomyInfo: 'معلومات التصنيف والوسوم', engagementInfo: 'تفاصيل التفاعل', dateInfo: 'جميع تواريخ العمل', moreInfo: 'عرض التفاصيل', openInfo: 'عرض التفاصيل', close: 'إغلاق', title: 'العنوان', slug: 'المعرّف النصي للرابط', summary: 'الملخص', media: 'نوع الوسائط', price: 'السعر', delivery: 'مدة التسليم بالأيام', none: 'غير متوفر', visibility: 'الظهور', workStatus: 'حالة العمل', featured: 'مميز', pinned: 'مثبت', designer: 'المصمم', reviewer: 'المراجع', unassigned: 'غير معيّن', unavailable: 'غير متاح حسب الصلاحية', uncategorized: 'غير مصنف', active: 'فعال', disabled: 'معطل', noTags: 'دون وسوم', tagsCount: (count: number) => `${formatYmNumber(count, props.locale)} وسوم`, views: 'المشاهدات', likes: 'الإعجابات', reports: 'البلاغات', hasReports: 'يوجد بلاغ واحد أو أكثر', image: 'صورة', video: 'فيديو', gallery: 'معرض صور', unknownMedia: 'غير محدد', public: 'عام', hidden: 'مخفي', yes: 'نعم', no: 'لا', edit: 'تحرير العمل', details: 'عرض التفاصيل', manageTaxonomy: 'إدارة التصنيف والوسوم', showing: (visible: string, total: string) => `عرض ${visible} من أصل ${total}`, summaryUnavailable: 'عرض — من أصل —', pagination: 'التنقل بين صفحات الأعمال', previous: 'السابق', next: 'التالي', pageOf: (page: string, last: string) => `الصفحة ${page} من ${last}` },
  en: { loading: 'Loading works', loadingCopy: 'Fetching the latest result matching the filters.', updating: 'Updating results while keeping the last consistent data…', error: 'Could not load works', retry: 'Retry', empty: 'No matching works.', emptyCopy: 'Reset the filters or create a new work.', reset: 'Reset filters', create: 'Create new work', selectPage: 'Select current page', selectWork: (title: string) => `Select ${title}`, work: 'Work', status: 'Status', team: 'Team', taxonomy: 'Category and tags', engagement: 'Engagement', metric: 'Engagement metric', date: 'Date type', dateHeading: 'Date', direction: 'Sort direction', descending: 'Descending', ascending: 'Ascending', viewControls: 'Card view controls', toggleDirection: 'Toggle sort direction', actions: 'Actions', workInfo: 'Work information', statusInfo: 'Status information', teamInfo: 'Team information', taxonomyInfo: 'Category and tag information', engagementInfo: 'Engagement details', dateInfo: 'All work dates', moreInfo: 'View details', openInfo: 'View details', close: 'Close', title: 'Title', slug: 'Slug', summary: 'Summary', media: 'Media type', price: 'Price', delivery: 'Delivery days', none: 'Unavailable', visibility: 'Visibility', workStatus: 'Work status', featured: 'Featured', pinned: 'Pinned', designer: 'Designer', reviewer: 'Reviewer', unassigned: 'Unassigned', unavailable: 'Unavailable for this permission scope', uncategorized: 'Uncategorized', active: 'Active', disabled: 'Disabled', noTags: 'No tags', tagsCount: (count: number) => `${formatYmNumber(count, props.locale)} tags`, views: 'Views', likes: 'Likes', reports: 'Reports', hasReports: 'One or more reports exist', image: 'Image', video: 'Video', gallery: 'Gallery', unknownMedia: 'Unspecified', public: 'Public', hidden: 'Hidden', yes: 'Yes', no: 'No', edit: 'Edit work', details: 'View details', manageTaxonomy: 'Manage category and tags', showing: (visible: string, total: string) => `Showing ${visible} of ${total}`, summaryUnavailable: 'Showing — of —', pagination: 'Works pagination', previous: 'Previous', next: 'Next', pageOf: (page: string, last: string) => `Page ${page} of ${last}` }
} as const
const text = computed(() => copies[props.locale] as TextCopy)
const metricOptions = computed(() => [{ value: 'views_count' as const, label: text.value.views }, { value: 'likes_count' as const, label: text.value.likes }, { value: 'reports_count' as const, label: text.value.reports }])
const dateOptions = computed(() => [{ value: 'created_at' as const, label: props.locale === 'ar' ? 'تاريخ الإنشاء' : 'Created at' }, { value: 'updated_at' as const, label: props.locale === 'ar' ? 'آخر تحديث' : 'Last updated' }, { value: 'submitted_at' as const, label: props.locale === 'ar' ? 'تاريخ الإرسال' : 'Submitted at' }, { value: 'reviewed_at' as const, label: props.locale === 'ar' ? 'تاريخ المراجعة' : 'Reviewed at' }, { value: 'approved_at' as const, label: props.locale === 'ar' ? 'تاريخ الاعتماد' : 'Approved at' }, { value: 'published_at' as const, label: props.locale === 'ar' ? 'تاريخ النشر' : 'Published at' }, { value: 'rejected_at' as const, label: props.locale === 'ar' ? 'تاريخ الرفض' : 'Rejected at' }, { value: 'hidden_at' as const, label: props.locale === 'ar' ? 'تاريخ الإخفاء' : 'Hidden at' }, { value: 'archived_at' as const, label: props.locale === 'ar' ? 'تاريخ الأرشفة' : 'Archived at' }])
const metricLabel = computed(() => metricOptions.value.find(option => option.value === props.metric)?.label || '')
const dateLabel = computed(() => dateOptions.value.find(option => option.value === props.dateField)?.label || '')
const currentControlKind = computed<'metric' | 'date'>(() => props.sort === props.metric ? 'metric' : 'date')
const footerAriaLabel = computed(() => props.summary
  ? text.value.showing(formatNumber(props.summary.visible_on_page), formatNumber(props.summary.total_filtered))
  : text.value.summaryUnavailable)
const allSelected = computed(() => props.items.length > 0 && props.items.every(work => props.selectedIds.includes(work.id)))
const isSelected = (id: number) => props.selectedIds.includes(id)
const formatNumber = (value: number) => formatYmNumber(value, props.locale)
const formatDate = (value: string | null) => formatYmDate(value, props.locale)
const formatDateTime = (value: string | null) => formatYmDateTime(value, props.locale)
function textDirection(value: string): 'rtl' | 'ltr' { return /[\u0600-\u06FF]/.test(value) ? 'rtl' : 'ltr' }
function mediaLabel(value: string | null): string { return value === 'image' ? text.value.image : value === 'video' ? text.value.video : value === 'gallery' ? text.value.gallery : text.value.unknownMedia }
function visibilityLabel(value: string): string { return value === 'public' ? text.value.public : text.value.hidden }
function yesNo(value: boolean): string { return value ? text.value.yes : text.value.no }
function statusLabel(value: string): string { const ar: Record<string, string> = { draft: 'مسودة', submitted: 'قيد المراجعة', in_review: 'تحت المراجعة', changes_requested: 'تعديلات مطلوبة', approved: 'معتمد', published: 'منشور', rejected: 'مرفوض', hidden: 'مخفي', archived: 'مؤرشف' }; const en: Record<string, string> = { draft: 'Draft', submitted: 'Submitted', in_review: 'In review', changes_requested: 'Changes requested', approved: 'Approved', published: 'Published', rejected: 'Rejected', hidden: 'Hidden', archived: 'Archived' }; return (props.locale === 'ar' ? ar : en)[value] || value }
function taxonomyName(entity: Entity): string { return props.locale === 'ar' ? entity.name_ar : entity.name_en }
function categoryLabel(work: WorkItem): string { if (work.taxonomy.category) return taxonomyName(work.taxonomy.category); if (work.taxonomy.category_tracking?.is_uncategorized) return text.value.uncategorized; if (work.taxonomy.category_tracking?.is_legacy_unmapped) return props.locale === 'ar' ? 'تصنيف قديم' : 'Legacy category'; return text.value.unavailable }
function tagsSummary(work: WorkItem): string { if (work.taxonomy.tags === null) return text.value.unavailable; return work.taxonomy.tags.length ? text.value.tagsCount(work.taxonomy.tags.length) : text.value.noTags }
function changeMetric(event: Event): void { const value = (event.target as HTMLSelectElement).value as MetricKey; if (metricOptions.value.some(option => option.value === value)) emit('metric-change', value) }
function changeDate(event: Event): void { const value = (event.target as HTMLSelectElement).value as DateKey; if (dateOptions.value.some(option => option.value === value)) emit('date-change', value) }
const emit = defineEmits<{ retry: []; reset: []; 'toggle-page': []; 'toggle-work': [work: WorkItem]; 'metric-change': [metric: MetricKey]; 'date-change': [date: DateKey]; 'direction-change': [kind: 'metric' | 'date']; details: [work: WorkItem]; taxonomy: [work: WorkItem]; page: [page: number] }>()
const icon = (paths: string[]) => defineComponent({ setup: () => () => h('svg', { viewBox: '0 0 24 24', 'aria-hidden': 'true' }, paths.map(d => h('path', { d }))) })
const FeaturedIcon = icon(['m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9Z'])
const PinIcon = icon(['m8 3 8 8-2 2 3 3-1 1-3-3-2 2-3-3-5 5-1-1 5-5-3-3Z'])
const MediaIcon = defineComponent({ props: { type: String }, setup: props => () => h('svg', { viewBox: '0 0 24 24', 'aria-hidden': 'true' }, props.type === 'video' ? [h('path', { d: 'M4 6h11v12H4zM15 10l5-3v10l-5-3z' })] : [h('rect', { x: 4, y: 5, width: 16, height: 14, rx: 2 }), h('path', { d: 'm6 16 4-4 3 3 2-2 3 3M9 9h.01' })]) })
const actionOverlay = (label: string, paths: string[], activate: () => void) => h(
  WorksIndexFloatingOverlay,
  { label, triggerAriaLabel: label, triggerClass: 'ym-smart-list__action', onActivate: activate },
  { trigger: () => h('svg', { viewBox: '0 0 24 24', 'aria-hidden': 'true' }, paths.map(d => h('path', { d }))) }
)
const ActionButtons = defineComponent({
  props: { work: { type: Object, required: true }, canEdit: Boolean, canDetails: Boolean, canTaxonomy: Boolean, text: { type: Object, required: true } },
  emits: ['details', 'taxonomy'],
  setup(p, { emit: send }) {
    return () => h('div', { class: 'ym-smart-list__actions' }, [
      p.canEdit ? actionOverlay(p.text.edit, ['m4 16-1 5 5-1L19 9l-4-4Z', 'm13 7 4 4'], () => navigateTo(`/admin/works/${(p.work as WorkItem).id}/edit`)) : null,
      p.canDetails ? actionOverlay(p.text.details, ['M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12Z', 'M12 9.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Z'], () => send('details')) : null,
      p.canTaxonomy ? actionOverlay(p.text.manageTaxonomy, ['M3 5h8l10 10-6 6L5 11Z', 'M8 8h.01'], () => send('taxonomy')) : null
    ])
  }
})

watch(
  () => [props.items, props.loading, props.locale],
  () => {
    if (typeof document !== 'undefined') document.dispatchEvent(new CustomEvent('ym:works-index-overlays-close'))
  },
  { flush: 'post' }
)
</script>

<style scoped>
.ym-smart-list { border: 1px solid var(--ym-card-border); border-radius: 18px; padding: 14px; color: var(--ym-text); background: var(--ym-card-bg); min-width: 0; }
.ym-smart-list__view-controls { display: none; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; border: 1px solid color-mix(in srgb, var(--ym-violet-electric, #8b5cf6) 26%, var(--ym-card-border)); border-radius: 14px; margin-bottom: 12px; padding: 11px; background: color-mix(in srgb, var(--ym-input-bg) 88%, transparent); }
.ym-smart-list__view-controls label { display: grid; gap: 5px; min-width: 0; color: var(--ym-muted); font-size: 12px; font-weight: 800; }
.ym-smart-list__view-controls select, .ym-smart-list__view-controls button { width: 100%; min-width: 0; min-height: 44px; border: 1px solid var(--ym-control-border); border-radius: 11px; padding: 0 10px; color: var(--ym-text); background: var(--ym-input-bg); font-size: 13px; }
.ym-smart-list__view-controls button { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: center; gap: 4px 8px; text-align: start; cursor: pointer; }
.ym-smart-list__view-controls button span { grid-column: 1 / -1; color: var(--ym-muted); font-size: 12px; }
.ym-smart-list__view-controls button i { color: var(--ym-violet-electric, #8b5cf6); font-size: 18px; font-style: normal; }
.ym-smart-list__update { border-radius: 11px; margin: 0 0 10px; padding: 9px 11px; font-size: 13px; font-weight: 750; }
.ym-smart-list__update.is-progress { color: var(--ym-violet-electric, #8b5cf6); background: color-mix(in srgb, var(--ym-violet-electric, #8b5cf6) 9%, transparent); }
.ym-smart-list__update.is-error { color: var(--ym-rose, #f43f5e); background: color-mix(in srgb, var(--ym-rose, #f43f5e) 10%, transparent); }
.ym-smart-list__update.is-warning { color: var(--ym-amber, #f59e0b); background: color-mix(in srgb, var(--ym-amber, #f59e0b) 10%, transparent); }
.ym-smart-list__update button { border: 0; padding: 3px 7px; color: inherit; background: transparent; font-weight: 900; text-decoration: underline; cursor: pointer; }
.ym-smart-list__desktop { width: 100%; min-width: 0; overflow: hidden; border-radius: 15px; }.ym-smart-list table { width: 100%; table-layout: fixed; border-collapse: separate; border-spacing: 0 7px; }.ym-smart-list col.is-select { width: 3.5%; }.ym-smart-list col.is-work { width: 18%; }.ym-smart-list col.is-status { width: 12%; }.ym-smart-list col.is-team { width: 14%; }.ym-smart-list col.is-taxonomy { width: 14%; }.ym-smart-list col.is-dynamic { width: 13%; }.ym-smart-list col.is-date { width: 14.5%; }.ym-smart-list col.is-actions { width: 11%; }
.ym-smart-list th, .ym-smart-list td { box-sizing: border-box; min-width: 0; padding: 10px 9px; text-align: start; vertical-align: middle; }.ym-smart-list th { position: sticky; top: 0; z-index: 3; height: 60px; border-block-start: 1px solid color-mix(in srgb, var(--ym-violet-electric, #8b5cf6) 38%, var(--ym-card-border)); border-block-end: 1px solid color-mix(in srgb, var(--ym-cyan, #22d3ee) 34%, var(--ym-card-border)); color: var(--ym-text); background: linear-gradient(115deg, color-mix(in srgb, var(--ym-dropdown-bg) 92%, var(--ym-violet, #7c3aed) 8%), color-mix(in srgb, var(--ym-dropdown-bg) 95%, var(--ym-cyan, #22d3ee) 5%)); box-shadow: inset 0 1px 0 color-mix(in srgb, #fff 11%, transparent), inset 0 -2px 0 color-mix(in srgb, var(--ym-cyan, #22d3ee) 14%, transparent); font-size: 14px; font-weight: 750; line-height: 1.4; }.ym-smart-list thead th:first-child { border-start-start-radius: 14px; }.ym-smart-list thead th:last-child { border-start-end-radius: 14px; }.ym-smart-list td { height: 80px; border-block: 1px solid color-mix(in srgb, var(--ym-card-border) 80%, var(--ym-violet-electric, #8b5cf6) 20%); color: var(--ym-muted); background: color-mix(in srgb, var(--ym-control-bg) 94%, transparent); font-size: 14px; }.ym-smart-list tbody td:first-child { border-inline-start: 3px solid var(--row-status, #64748b); border-start-start-radius: 13px; border-end-start-radius: 13px; }.ym-smart-list tbody td:last-child { border-start-end-radius: 13px; border-end-end-radius: 13px; }.ym-smart-list tbody tr { --row-status: #64748b; }.ym-smart-list tbody tr.is-status-published { --row-status: var(--ym-emerald, #10b981); }.ym-smart-list tbody tr.is-status-approved { --row-status: var(--ym-cyan, #22d3ee); }.ym-smart-list tbody tr.is-status-submitted, .ym-smart-list tbody tr.is-status-in_review, .ym-smart-list tbody tr.is-status-changes_requested { --row-status: var(--ym-amber, #f59e0b); }.ym-smart-list tbody tr.is-status-rejected { --row-status: var(--ym-rose, #f43f5e); }.ym-smart-list tbody tr:hover { filter: drop-shadow(0 8px 12px color-mix(in srgb, var(--ym-violet, #7c3aed) 10%, transparent)); }
.ym-smart-list th:not(:last-child), .ym-smart-list td:not(:last-child) { border-inline-end: 1px solid color-mix(in srgb, var(--ym-card-border) 88%, #8b5cf6 12%); }
.ym-smart-list th:not(:last-child)::after { content: ''; position: absolute; inset-block: 13px; inset-inline-end: -1px; width: 1px; border-radius: 999px; background: linear-gradient(180deg, transparent, color-mix(in srgb, #8b5cf6 30%, var(--ym-card-border)), transparent); pointer-events: none; }
.ym-smart-list tbody tr:hover td { border-block-color: color-mix(in srgb, var(--ym-violet-electric, #8b5cf6) 34%, var(--ym-card-border)); background: color-mix(in srgb, var(--ym-control-bg) 90%, var(--ym-violet, #7c3aed) 10%); }
.ym-smart-list th.is-select, .ym-smart-list td.is-select, .ym-smart-list th.is-dynamic, .ym-smart-list td.is-dynamic, .ym-smart-list th.is-date, .ym-smart-list td.is-date, .ym-smart-list th.is-actions, .ym-smart-list td.is-actions { text-align: center; }.ym-smart-list th.is-select, .ym-smart-list th.is-actions { vertical-align: middle; }.ym-smart-list th.is-work, .ym-smart-list td.is-work, .ym-smart-list th.is-status, .ym-smart-list td.is-status, .ym-smart-list th.is-team, .ym-smart-list td.is-team, .ym-smart-list th.is-taxonomy, .ym-smart-list td.is-taxonomy { text-align: start; }.ym-smart-list td.is-work :deep(.ym-floating-overlay), .ym-smart-list td.is-status :deep(.ym-floating-overlay), .ym-smart-list td.is-team :deep(.ym-floating-overlay), .ym-smart-list td.is-taxonomy :deep(.ym-floating-overlay) { width: 100%; }.ym-smart-list td.is-dynamic :deep(.ym-floating-overlay), .ym-smart-list td.is-date :deep(.ym-floating-overlay) { justify-content: center; }.ym-smart-list input[type=checkbox] { width: 18px; height: 18px; accent-color: #7c3aed; }
.ym-smart-list__head-title { display: block; margin-bottom: 3px; color: var(--ym-muted); font-size: 12.5px; font-weight: 750; line-height: 1.25; }.ym-smart-list__head-control { display: grid; width: 100%; min-height: 31px; grid-template-columns: minmax(0, 1fr) 30px; align-items: stretch; gap: 0; border: 1px solid color-mix(in srgb, var(--ym-control-border) 76%, var(--ym-violet-electric, #8b5cf6) 24%); border-radius: 9px; background: color-mix(in srgb, var(--ym-input-bg) 72%, transparent); box-shadow: inset 0 1px 0 color-mix(in srgb, #fff 8%, transparent); }.ym-smart-list__head-control label { display: block; min-width: 0; }.ym-smart-list__head-control select { display: block; width: 100%; min-width: 0; min-height: 30px; border: 0; border-radius: 8px 0 0 8px; padding-inline: 7px 3px; color: var(--ym-text); background: transparent; font-size: 12px; font-weight: 800; }.ym-smart-list__head-control button { display: grid; width: 30px; min-height: 30px; place-items: center; border: 0; border-inline-start: 1px solid color-mix(in srgb, var(--ym-control-border) 72%, transparent); border-radius: 0 8px 8px 0; padding: 0; color: var(--ym-violet-electric, #8b5cf6); background: transparent; font-size: 16px; cursor: pointer; }
.ym-smart-list th.is-dynamic, .ym-smart-list th.is-date { padding-block: 4px; }
.ym-smart-list__work, .ym-smart-list__status, .ym-smart-list__team, .ym-smart-list__taxonomy { display: grid; gap: 4px; min-width: 0; }.ym-smart-list__work strong { overflow: hidden; color: var(--ym-text); font-size: 15px; font-weight: 800; text-overflow: ellipsis; white-space: nowrap; }.ym-smart-list__work small { display: flex; align-items: center; gap: 5px; color: var(--ym-muted); font-size: 13px; }.ym-smart-list__work svg, .ym-smart-list__status svg { width: 15px; height: 15px; fill: none; stroke: currentColor; stroke-width: 1.8; }
.ym-smart-list__status b { position: relative; width: fit-content; border-radius: 999px; padding: 4px 9px; color: #475569; background: color-mix(in srgb, #64748b 15%, transparent); font-size: 12px; }.ym-smart-list__status b::before { display: inline-block; width: 6px; height: 6px; border-radius: 50%; margin-inline-end: 5px; background: currentColor; content: ''; box-shadow: 0 0 8px currentColor; }.ym-smart-list__status b.is-published { color: #059669; background: color-mix(in srgb, var(--ym-emerald, #10b981) 13%, transparent); }.ym-smart-list__status b.is-approved { color: #0891b2; background: color-mix(in srgb, var(--ym-cyan, #22d3ee) 12%, transparent); }.ym-smart-list__status b.is-rejected { color: #e11d48; background: color-mix(in srgb, var(--ym-rose, #f43f5e) 11%, transparent); }.ym-smart-list__status b.is-submitted, .ym-smart-list__status b.is-in_review, .ym-smart-list__status b.is-changes_requested { color: #b45309; background: color-mix(in srgb, var(--ym-amber, #f59e0b) 13%, transparent); }.ym-smart-list__status small { display: flex; align-items: center; gap: 5px; font-size: 13px; }
.ym-smart-list__team small { font-size: 12.5px; }.ym-smart-list__team strong { overflow: hidden; color: var(--ym-text); font-size: 14px; text-overflow: ellipsis; white-space: nowrap; }.ym-smart-list__taxonomy strong { overflow: hidden; color: var(--ym-text); font-size: 14px; text-overflow: ellipsis; white-space: nowrap; }.ym-smart-list__taxonomy small { font-size: 12.5px; }
.ym-smart-list__number { display: inline-grid; min-width: 50px; min-height: 36px; direction: ltr; unicode-bidi: isolate; place-items: center; border-radius: 10px; color: var(--ym-text); background: var(--ym-input-bg); font-weight: 850; font-variant-numeric: tabular-nums; }.ym-smart-list__number.is-alert { color: #e11d48; background: color-mix(in srgb, #e11d48 9%, transparent); }.ym-smart-list__date { direction: ltr; unicode-bidi: isolate; color: var(--ym-text); font-size: 14.5px; font-weight: 700; font-variant-numeric: tabular-nums; letter-spacing: .01em; }
.ym-smart-list .is-date-value { direction: ltr; unicode-bidi: isolate; font-weight: 700; font-variant-numeric: tabular-nums; letter-spacing: .01em; }
.ym-smart-list__popover-list { display: grid; gap: 8px; margin: 0; }.ym-smart-list__popover-list > div { display: grid; gap: 3px; border-bottom: 1px solid var(--ym-card-border); padding-bottom: 8px; }.ym-smart-list__popover-list > div:last-child { border-bottom: 0; padding-bottom: 0; }.ym-smart-list__popover-list dt { color: var(--ym-muted); font-size: 12px; }.ym-smart-list__popover-list dd { margin: 0; color: var(--ym-text); font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }.ym-smart-list__popover-list .is-alert dd { color: #e11d48; }.ym-smart-list__taxonomy-detail { display: grid; gap: 7px; }.ym-smart-list__taxonomy-detail p { margin: 0; color: var(--ym-muted); font-size: 13px; }.ym-smart-list__taxonomy-detail ul { display: flex; flex-wrap: wrap; gap: 6px; margin: 0; padding: 0; list-style: none; }.ym-smart-list__taxonomy-detail li { border-radius: 999px; padding: 5px 8px; background: color-mix(in srgb, #8b5cf6 10%, transparent); font-size: 12px; }.ym-smart-list__taxonomy-detail li.is-disabled { color: #b45309; background: color-mix(in srgb, #f59e0b 11%, transparent); }
.ym-smart-list :deep(.ym-smart-list__actions) { display: flex; flex-wrap: nowrap; justify-content: center; gap: 6px; }.ym-smart-list :deep(.ym-smart-list__actions .ym-floating-overlay) { display: inline-flex; flex: 0 0 36px; }.ym-smart-list :deep(.ym-smart-list__action) { display: grid; width: 36px; height: 36px; place-items: center; border: 1px solid var(--ym-control-border); border-radius: 10px; color: var(--ym-muted); background: var(--ym-input-bg); cursor: pointer; transition: transform .16s ease, border-color .16s ease, color .16s ease, box-shadow .16s ease; }.ym-smart-list :deep(.ym-smart-list__actions svg) { width: 18px; height: 18px; fill: none; stroke: currentColor; stroke-width: 1.8; stroke-linecap: round; stroke-linejoin: round; }.ym-smart-list :deep(.ym-smart-list__action:hover), .ym-smart-list :deep(.ym-smart-list__action:focus-visible) { color: var(--ym-violet, #7c3aed); border-color: var(--ym-violet-electric, #8b5cf6); box-shadow: 0 0 16px color-mix(in srgb, var(--ym-violet, #7c3aed) 16%, transparent); }.ym-smart-list :deep(.ym-smart-list__action:active) { transform: scale(.97); }.ym-smart-list :deep(.ym-smart-list__action:focus-visible) { outline: 3px solid color-mix(in srgb, #8b5cf6 40%, transparent); outline-offset: 2px; }
.ym-smart-list__mobile { display: none; gap: 12px; }.ym-smart-list__mobile article { display: grid; gap: 11px; border: 1px solid color-mix(in srgb, var(--ym-card-border) 76%, var(--ym-violet-electric, #8b5cf6) 24%); border-radius: 16px; padding: 15px; background: linear-gradient(145deg, color-mix(in srgb, var(--ym-input-bg) 94%, var(--ym-violet, #7c3aed) 6%), var(--ym-input-bg)); box-shadow: 0 10px 24px rgba(2,6,23,.08), inset 0 1px 0 color-mix(in srgb, #fff 8%, transparent); transition: transform .18s ease, border-color .18s ease, box-shadow .18s ease; }.ym-smart-list__mobile article:hover { transform: translateY(-2px); border-color: color-mix(in srgb, var(--ym-violet-electric, #8b5cf6) 42%, var(--ym-card-border)); box-shadow: 0 14px 30px color-mix(in srgb, var(--ym-violet, #7c3aed) 12%, rgba(2,6,23,.1)); }.ym-smart-list__mobile article > header { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: start; gap: 10px; }.ym-smart-list__mobile article > header > div { display: grid; gap: 4px; min-width: 0; }.ym-smart-list__mobile article > header > div strong { color: var(--ym-text); font-size: 16px; line-height: 1.4; }.ym-smart-list__mobile article > header svg, .ym-smart-list__mobile-meta svg { width: 16px; fill: none; stroke: currentColor; }.ym-smart-list__mobile-meta { display: flex; align-items: center; justify-content: space-between; gap: 10px; color: var(--ym-muted); font-size: 13.5px; }.ym-smart-list__mobile-meta span { display: inline-flex; align-items: center; gap: 5px; }.ym-smart-list__mobile dl { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; margin: 0; }.ym-smart-list__mobile dl > div { min-width: 0; border-radius: 11px; padding: 9px; background: color-mix(in srgb, var(--ym-card-bg) 60%, transparent); }.ym-smart-list__mobile dt { color: var(--ym-muted); font-size: 12.5px; font-weight: 750; }.ym-smart-list__mobile dd { margin: 4px 0 0; color: var(--ym-text); font-size: 14px; overflow-wrap: anywhere; }.ym-smart-list__mobile dd.is-team-lines { display: grid; gap: 3px; }.ym-smart-list__mobile dd.is-number { font-size: 17px; font-weight: 900; font-variant-numeric: tabular-nums; }.ym-smart-list__mobile footer { display: flex; align-items: center; justify-content: space-between; gap: 10px; border-top: 1px solid var(--ym-card-border); padding-top: 10px; }.ym-smart-list__more { display: inline-flex; min-height: 40px; align-items: center; border-radius: 10px; padding: 0 11px; color: var(--ym-violet, #7c3aed); background: color-mix(in srgb, var(--ym-violet-electric, #8b5cf6) 10%, transparent); font-size: 13.5px; font-weight: 800; }
.ym-smart-list__state { display: grid; min-height: 280px; place-items: center; align-content: center; gap: 10px; text-align: center; }.ym-smart-list__state strong { font-size: 17px; }.ym-smart-list__state p { max-width: 420px; margin: 0; color: var(--ym-muted); font-size: 14px; }.ym-smart-list__state button, .ym-smart-list__state a { display: inline-flex; min-height: 40px; align-items: center; border: 1px solid var(--ym-control-border); border-radius: 10px; margin: 5px; padding: 0 13px; color: var(--ym-text); background: var(--ym-input-bg); text-decoration: none; }.ym-smart-list__state.is-error strong { color: #e11d48; }.ym-smart-list__spinner { width: 34px; height: 34px; border: 3px solid color-mix(in srgb, #8b5cf6 18%, transparent); border-top-color: #8b5cf6; border-radius: 50%; animation: spin .8s linear infinite; }
.ym-smart-list__pagination { display: flex; align-items: center; justify-content: space-between; gap: 14px; border-top: 1px solid var(--ym-card-border); margin-top: 12px; padding-top: 13px; color: var(--ym-muted); font-size: 13px; font-variant-numeric: tabular-nums; }.ym-smart-list__pagination nav { display: flex; align-items: center; gap: 9px; }.ym-smart-list__pagination button { min-height: 38px; border: 1px solid var(--ym-control-border); border-radius: 10px; padding: 0 12px; color: var(--ym-text); background: var(--ym-input-bg); }.ym-smart-list__pagination button:disabled { opacity: .45; }.ym-smart-list__pagination b { direction: ltr; unicode-bidi: isolate; color: var(--ym-text); font-size: 13px; }
.sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }.ym-smart-list button:focus-visible, .ym-smart-list select:focus-visible, .ym-smart-list input:focus-visible, .ym-smart-list a:focus-visible { outline: 3px solid color-mix(in srgb, #8b5cf6 42%, transparent); outline-offset: 2px; }
@keyframes spin { to { transform: rotate(360deg); } }
@media (max-width: 1100px) { .ym-smart-list__view-controls { display: grid; }.ym-smart-list__desktop { display: none; }.ym-smart-list__mobile { display: grid; }.ym-smart-list :deep(.ym-smart-list__actions .ym-floating-overlay) { flex-basis: 40px; }.ym-smart-list :deep(.ym-smart-list__action) { width: 40px; height: 40px; }.ym-smart-list__pagination button { min-height: 40px; } }
@media (max-width: 600px) { .ym-smart-list { padding: 10px; }.ym-smart-list__view-controls { grid-template-columns: 1fr; }.ym-smart-list__mobile article > header { grid-template-columns: auto minmax(0, 1fr) auto; }.ym-smart-list__mobile dl { grid-template-columns: repeat(2, minmax(0, 1fr)); }.ym-smart-list__mobile footer, .ym-smart-list__pagination { align-items: stretch; flex-direction: column; }.ym-smart-list__pagination nav { justify-content: space-between; }.ym-smart-list__pagination nav b { text-align: center; } }
@media (prefers-reduced-motion: reduce) { .ym-smart-list__spinner { animation: none; }.ym-smart-list__mobile article, .ym-smart-list tbody tr, .ym-smart-list__number { transition: none; }.ym-smart-list__mobile article:hover, .ym-smart-list__number:hover { transform: none; } }
.ym-smart-list { border-color: color-mix(in srgb, var(--ym-card-border) 82%, #8b5cf6 18%); background: linear-gradient(145deg, color-mix(in srgb, var(--ym-card-bg) 97%, #8b5cf6 3%), var(--ym-card-bg)); box-shadow: 0 16px 38px rgba(2, 6, 23, .1), inset 0 1px 0 color-mix(in srgb, #fff 8%, transparent); }
.ym-smart-list__desktop { border-color: color-mix(in srgb, var(--ym-card-border) 72%, #8b5cf6 28%); box-shadow: 0 9px 24px rgba(2, 6, 23, .08), inset 0 1px 0 color-mix(in srgb, #fff 7%, transparent); }
.ym-smart-list th:not(:last-child), .ym-smart-list td:not(:last-child) { border-inline-end-color: color-mix(in srgb, var(--ym-card-border) 86%, #8b5cf6 14%); }
.ym-smart-list th:not(:last-child)::after { opacity: .55; box-shadow: 0 0 7px color-mix(in srgb, #8b5cf6 18%, transparent); }
.ym-smart-list tbody tr { transition: background .18s ease, box-shadow .18s ease; }
.ym-smart-list tbody tr:hover { box-shadow: inset 3px 0 0 color-mix(in srgb, #8b5cf6 58%, transparent), inset -3px 0 0 color-mix(in srgb, #8b5cf6 58%, transparent); }
.ym-smart-list__number { border: 1px solid color-mix(in srgb, var(--ym-control-border) 82%, #8b5cf6 18%); box-shadow: inset 0 1px 0 color-mix(in srgb, #fff 8%, transparent), 0 4px 10px rgba(2, 6, 23, .05); transition: transform .16s ease, border-color .16s ease, box-shadow .16s ease; }
.ym-smart-list__number:hover { transform: translateY(-1px); border-color: color-mix(in srgb, #8b5cf6 48%, var(--ym-control-border)); box-shadow: 0 7px 16px color-mix(in srgb, #8b5cf6 11%, transparent); }
</style>
