<template>
  <WorksDrawerShell :open="open&&Boolean(item)" :locale="locale" size="details" :title-id="titleId" :close-label="t.close" @request-close="$emit('close')">
    <template #header><div class="head"><span>{{ t.eyebrow }}</span><h2 :id="titleId">{{ eventLabel }}</h2><small v-if="item" dir="ltr">#{{ number(item.audit_event_id) }}</small></div></template>
    <div v-if="item" class="content">
      <section><h3>{{ t.event }}</h3><dl><div><dt>{{ t.id }}</dt><dd dir="ltr">{{ safe(item.id) }}</dd></div><div><dt>{{ t.auditId }}</dt><dd dir="ltr">{{ number(item.audit_event_id) }}</dd></div><div><dt>{{ t.type }}</dt><dd dir="ltr">{{ safe(item.event_type) }}</dd></div><div><dt>{{ t.group }}</dt><dd dir="ltr">{{ safe(item.event_group) }}</dd></div><div><dt>{{ t.time }}</dt><dd dir="ltr">{{ dateTime(item.event_at) }}</dd></div><div><dt>{{ t.action }}</dt><dd dir="ltr">{{ value(item.action) }}</dd></div><div><dt>{{ t.outcome }}</dt><dd dir="ltr">{{ value(item.outcome) }}</dd></div><div><dt>{{ t.severity }}</dt><dd dir="ltr">{{ value(item.severity) }}</dd></div></dl></section>
      <section><h3>{{ t.actor }}</h3><dl><div><dt>{{ t.id }}</dt><dd dir="ltr">{{ item.actor?.id==null?t.unavailable:number(item.actor.id) }}</dd></div><div><dt>{{ t.name }}</dt><dd>{{ safe(item.actor?.name||t.unavailable) }}</dd></div><div><dt>{{ t.role }}</dt><dd dir="ltr">{{ safe(item.actor?.role||t.unavailable) }}</dd></div><div><dt>{{ t.actorMissing }}</dt><dd>{{ yesNo(item.activity_flags.actor_missing) }}</dd></div></dl></section>
      <section><h3>{{ t.target }}</h3><dl><div><dt>{{ t.type }}</dt><dd dir="ltr">{{ safe(item.target.type) }}</dd></div><div><dt>{{ t.id }}</dt><dd dir="ltr">{{ item.target.id==null?t.unavailable:number(item.target.id) }}</dd></div><div><dt>{{ t.scope }}</dt><dd dir="ltr">{{ safe(definition?.target_scope??item.target.scope) }}</dd></div></dl></section>
      <section><h3>{{ t.work }}</h3><dl><div><dt>{{ t.id }}</dt><dd dir="ltr">{{ item.work?number(item.work.id):t.unavailable }}</dd></div><div><dt>{{ t.title }}</dt><dd>{{ safe(item.work?.title||t.unavailable) }}</dd></div><div><dt>{{ t.slug }}</dt><dd dir="ltr">{{ safe(item.work?.slug||t.unavailable) }}</dd></div><div><dt>{{ t.status }}</dt><dd dir="ltr">{{ safe(item.work?.status||t.unavailable) }}</dd></div><div><dt>{{ t.visibility }}</dt><dd dir="ltr">{{ safe(item.work?.visibility_status||t.unavailable) }}</dd></div><div><dt>{{ t.media }}</dt><dd>{{ media(item.work?.media_type) }}</dd></div></dl></section>
      <section><h3>{{ t.resultFlags }}</h3><dl><div><dt>{{ t.outcome }}</dt><dd>{{ value(item.outcome) }}</dd></div><div><dt>{{ t.severity }}</dt><dd>{{ value(item.severity) }}</dd></div><div><dt>{{ t.requiresWork }}</dt><dd>{{ yesNo(item.activity_flags.requires_work) }}</dd></div><div><dt>{{ t.needsAttention }}</dt><dd>{{ yesNo(item.activity_flags.needs_attention) }}</dd></div><div><dt>{{ t.actorMissing }}</dt><dd>{{ yesNo(item.activity_flags.actor_missing) }}</dd></div><div><dt>{{ t.workMissing }}</dt><dd>{{ yesNo(item.activity_flags.work_missing) }}</dd></div></dl></section>
    </div>
    <template v-if="canOpenWork&&item?.work" #footer><div class="footer"><NuxtLink :to="`/admin/works/all?work=${item.work.id}`">{{ t.openWork }}</NuxtLink></div></template>
  </WorksDrawerShell>
</template>
<script setup lang="ts">
import{computed}from'vue';import WorksDrawerShell from'~/components/works/drawers/WorksDrawerShell.vue';import{formatYmDateTime,formatYmNumber,toLatinDigits}from'~/utils/ymFormatting'
type Locale='ar'|'en';interface Item{id:string;source:string;audit_event_id:number;event_type:string;event_key:string;event_group:string;event_label_ar:string;event_label_en:string;event_at:string;severity:string|null;action:string|null;outcome:string|null;actor:{id:number|null;name:string;role:string|null}|null;target:{type:string;id:number|null;scope:string};work:{id:number;title:string;slug:string;status:string;visibility_status:string;media_type:string|null}|null;activity_flags:{requires_work:boolean;needs_attention:boolean;actor_missing:boolean;work_missing:boolean}}interface Definition{event_type:string;event_key:string;event_group:string;label_ar:string;label_en:string;target_scope:string;requires_work:boolean;needs_attention:boolean}
const props=defineProps<{open:boolean;item:Item|null;definition:Definition|null;locale:Locale;canOpenWork:boolean;returnFocus:HTMLElement|null}>();defineEmits<{close:[]}>();const titleId='ym-works-audit-drawer-title';const copy={ar:{eyebrow:'تفاصيل حدث التدقيق',close:'إغلاق التفاصيل',event:'تعريف الحدث',id:'المعرّف',auditId:'معرّف التدقيق',type:'النوع',group:'المجموعة',time:'الوقت',action:'الإجراء',outcome:'النتيجة',severity:'الشدة',actor:'الفاعل',name:'الاسم',role:'الدور',actorMissing:'الفاعل مفقود',target:'الهدف',scope:'النطاق',work:'العمل',title:'العنوان',slug:'المعرّف النصي',status:'الحالة',visibility:'الظهور',media:'الوسائط',resultFlags:'النتيجة والمؤشرات',requiresWork:'يتطلب عملًا',needsAttention:'يحتاج انتباهًا',workMissing:'العمل مفقود',openWork:'فتح تفاصيل العمل',unavailable:'غير متاح',yes:'نعم',no:'لا'},en:{eyebrow:'Audit event details',close:'Close details',event:'Event definition',id:'ID',auditId:'Audit ID',type:'Type',group:'Group',time:'Time',action:'Action',outcome:'Outcome',severity:'Severity',actor:'Actor',name:'Name',role:'Role',actorMissing:'Actor missing',target:'Target',scope:'Scope',work:'Work',title:'Title',slug:'Text identifier',status:'Status',visibility:'Visibility',media:'Media',resultFlags:'Result and flags',requiresWork:'Requires work',needsAttention:'Needs attention',workMissing:'Work missing',openWork:'Open work details',unavailable:'Unavailable',yes:'Yes',no:'No'}}as const;const t=computed(()=>copy[props.locale]);const eventLabel=computed(()=>toLatinDigits(props.definition?(props.locale==='ar'?props.definition.label_ar:props.definition.label_en):props.item?(props.locale==='ar'?props.item.event_label_ar:props.item.event_label_en):''))
function safe(v:string|number){return toLatinDigits(v)}function number(v:number){return formatYmNumber(Number.isFinite(v)?v:0,props.locale)}function dateTime(v:string){return formatYmDateTime(v,props.locale)}function value(v:string|null){return v?.trim()?safe(v):t.value.unavailable}function yesNo(v:boolean){return v?t.value.yes:t.value.no}function media(v:string|null|undefined){if(v==='image')return props.locale==='ar'?'صورة':'Image';if(v==='video')return props.locale==='ar'?'فيديو':'Video';return v?safe(v):t.value.unavailable}
</script>
<style scoped>
.head{display:grid;gap:4px}.head span{color:var(--ym-drawer-electric);font-size:12px;font-weight:850}.head h2{margin:0;color:var(--ym-drawer-text);font-size:21px}.head small{color:var(--ym-drawer-muted);font-weight:700}.content{display:grid;gap:12px}.content section{border:1px solid var(--ym-drawer-soft-border);border-radius:16px;padding:14px;background:var(--ym-drawer-card)}h3{margin:0 0 10px;color:var(--ym-drawer-text);font-size:16px}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0}dl div{min-width:0;border-bottom:1px solid var(--ym-drawer-soft-border);padding:7px}dt{color:var(--ym-drawer-muted);font-size:12px}dd{margin:3px 0 0;color:var(--ym-drawer-text);font-size:13px;font-weight:750;overflow-wrap:anywhere}.footer{display:flex;justify-content:flex-end}.footer a{border-radius:11px;padding:10px 14px;color:#fff;background:var(--ym-drawer-violet);font-weight:850;text-decoration:none}.footer a:focus-visible{outline:3px solid var(--ym-drawer-electric);outline-offset:2px}@media(max-width:640px){dl{grid-template-columns:1fr}}
</style>
