<template>
  <WorksDrawerShell :open="open&&Boolean(item)" :locale="locale" size="details" :title-id="titleId" :close-label="t.close" @request-close="$emit('close')">
    <template #header><div class="head"><span>{{ t.eyebrow }}</span><h2 :id="titleId">{{ safe(item?.event_label||'') }}</h2><small v-if="item" dir="ltr">{{ dateTime(item.event_at) }}</small></div></template>
    <div v-if="item" class="content">
      <section><h3>{{ t.event }}</h3><dl><div><dt>{{ t.id }}</dt><dd dir="ltr">{{ safe(item.id) }}</dd></div><div><dt>{{ t.type }}</dt><dd dir="ltr">{{ safe(item.event_type) }}</dd></div><div><dt>{{ t.time }}</dt><dd dir="ltr">{{ dateTime(item.event_at) }}</dd></div></dl></section>
      <section><h3>{{ t.work }}</h3><dl><div><dt>{{ t.workId }}</dt><dd dir="ltr">{{ number(item.work_id) }}</dd></div><div><dt>{{ t.title }}</dt><dd>{{ safe(item.title) }}</dd></div><div><dt>{{ t.slug }}</dt><dd dir="ltr">{{ safe(item.slug) }}</dd></div><div><dt>{{ t.media }}</dt><dd>{{ media(item.media_type) }}</dd></div></dl></section>
      <section><h3>{{ t.workflow }}</h3><dl><div><dt>{{ t.status }}</dt><dd>{{ status(item.status) }}</dd></div><div><dt>{{ t.visibility }}</dt><dd>{{ visibility(item.visibility_status) }}</dd></div></dl></section>
      <section><h3>{{ t.people }}</h3><dl><div><dt>{{ t.designer }}</dt><dd>{{ person(item.designer) }}</dd></div><div><dt>{{ t.reviewer }}</dt><dd>{{ person(item.reviewer) }}</dd></div><div><dt>{{ t.category }}</dt><dd dir="ltr">{{ item.category_id===null?t.unavailable:number(item.category_id) }}</dd></div></dl></section>
      <section><h3>{{ t.engagement }}</h3><dl><div><dt>{{ t.views }}</dt><dd>{{ number(item.views_count) }}</dd></div><div><dt>{{ t.likes }}</dt><dd>{{ number(item.likes_count) }}</dd></div><div><dt>{{ t.reports }}</dt><dd>{{ number(item.reports_count) }}</dd></div></dl></section>
      <section><h3>{{ t.flags }}</h3><dl><div><dt>{{ t.reviewEvent }}</dt><dd>{{ yesNo(item.activity_flags.is_review_event) }}</dd></div><div><dt>{{ t.visibilityEvent }}</dt><dd>{{ yesNo(item.activity_flags.is_visibility_event) }}</dd></div><div><dt>{{ t.reported }}</dt><dd>{{ yesNo(item.activity_flags.is_reported) }}</dd></div><div><dt>{{ t.promoted }}</dt><dd>{{ yesNo(item.activity_flags.is_promoted) }}</dd></div><div><dt>{{ t.attention }}</dt><dd>{{ yesNo(item.activity_flags.needs_attention) }}</dd></div></dl></section>
    </div>
  </WorksDrawerShell>
</template>
<script setup lang="ts">
import{computed}from'vue';import WorksDrawerShell from'~/components/works/drawers/WorksDrawerShell.vue';import{formatYmDateTime,formatYmNumber,toLatinDigits}from'~/utils/ymFormatting';type Locale='ar'|'en';interface User{id:number;name:string}interface Item{id:string;work_id:number;event_type:string;event_label:string;event_at:string;title:string;slug:string;status:string;visibility_status:'public'|'hidden';media_type:string|null;designer:User|null;reviewer:User|null;category_id:number|null;reports_count:number;views_count:number;likes_count:number;activity_flags:{is_review_event:boolean;is_visibility_event:boolean;is_reported:boolean;is_promoted:boolean;needs_attention:boolean}}
const props=defineProps<{open:boolean;item:Item|null;locale:Locale}>();defineEmits<{close:[]}>();const titleId='ym-works-lifecycle-drawer-title';const copy={ar:{eyebrow:'تفاصيل دورة حياة العمل',close:'إغلاق التفاصيل',event:'تعريف الحدث',id:'المعرّف',type:'نوع الحدث',time:'الوقت',work:'العمل',workId:'معرّف العمل',title:'العنوان',slug:'المعرّف النصي',media:'الوسائط',workflow:'سير العمل والظهور',status:'الحالة',visibility:'الظهور',people:'الأشخاص والتصنيف',designer:'المصمم',reviewer:'المراجع',category:'التصنيف',engagement:'التفاعل',views:'المشاهدات',likes:'الإعجابات',reports:'البلاغات',flags:'مؤشرات النشاط',reviewEvent:'حدث مراجعة',visibilityEvent:'حدث ظهور',reported:'عليه بلاغات',promoted:'مروّج',attention:'يحتاج انتباهًا',unavailable:'غير متاح',yes:'نعم',no:'لا'},en:{eyebrow:'Work lifecycle details',close:'Close details',event:'Event identity',id:'ID',type:'Event type',time:'Time',work:'Work',workId:'Work ID',title:'Title',slug:'Text identifier',media:'Media',workflow:'Workflow and visibility',status:'Status',visibility:'Visibility',people:'People and category',designer:'Designer',reviewer:'Reviewer',category:'Category',engagement:'Engagement',views:'Views',likes:'Likes',reports:'Reports',flags:'Activity flags',reviewEvent:'Review event',visibilityEvent:'Visibility event',reported:'Reported',promoted:'Promoted',attention:'Needs attention',unavailable:'Unavailable',yes:'Yes',no:'No'}}as const;const t=computed(()=>copy[props.locale]);const arStatus:Record<string,string>={draft:'مسودة',submitted:'مرسل',in_review:'قيد المراجعة',changes_requested:'تعديلات مطلوبة',approved:'معتمد',published:'منشور',rejected:'مرفوض',hidden:'مخفي',archived:'مؤرشف'}
function safe(v:string|number){return toLatinDigits(v)}function number(v:number){return formatYmNumber(Number.isFinite(v)?v:0,props.locale)}function dateTime(v:string){return formatYmDateTime(v,props.locale)}function status(v:string){return props.locale==='ar'?(arStatus[v]||safe(v)):safe(v.replaceAll('_',' '))}function visibility(v:string){return v==='public'?(props.locale==='ar'?'عام':'Public'):(props.locale==='ar'?'مخفي':'Hidden')}function media(v:string|null){if(v==='image')return props.locale==='ar'?'صورة':'Image';if(v==='video')return props.locale==='ar'?'فيديو':'Video';return v?safe(v):t.value.unavailable}function person(v:User|null){return v?`${safe(v.name)} #${number(v.id)}`:t.value.unavailable}function yesNo(v:boolean){return v?t.value.yes:t.value.no}
</script>
<style scoped>
.head{display:grid;gap:4px}.head span{color:var(--ym-drawer-electric);font-size:12px;font-weight:850}.head h2{margin:0;color:var(--ym-drawer-text);font-size:21px}.head small{color:var(--ym-drawer-muted)}.content{display:grid;gap:12px}.content section{border:1px solid var(--ym-drawer-soft-border);border-radius:16px;padding:14px;background:var(--ym-drawer-card)}h3{margin:0 0 10px;color:var(--ym-drawer-text);font-size:16px}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0}dl div{min-width:0;border-bottom:1px solid var(--ym-drawer-soft-border);padding:7px}dt{color:var(--ym-drawer-muted);font-size:12px}dd{margin:3px 0 0;color:var(--ym-drawer-text);font-size:13px;font-weight:750;overflow-wrap:anywhere}@media(max-width:640px){dl{grid-template-columns:1fr}}
</style>
